---
title: "Urban post-growth in the lens of the Open Manufacturing Ecosystems"
format: html
bibliography: references.bib
---


# Proposal context, positioning and objective(s)

### Towards circular cities: a promise to fulfill

The circular economy concept acts as an umbrella concept in the policy, industrial and scientific arenas framing the narrative of waste and resource management for prolonging the resource use [@]. 
Nevertheless, it is also as a contested concept [@CalistoFriant2020; @rodl2022; @corvellec2021] because it is unclear the implementability, there are contradictions with the thermodynamic constraints and biophysical flows [@Giampietro2020] and the lack of social inclusion [@ChiappettaJabbour2019].
CE critics rely on the ecological modernization arguments that build on capitalist economic growth narratives. 
Many cities have taken up the resource management discourse to design circular economy action plans, which aim to reduce urban environmental impacts.
Working to make cities more circular implies adopting a particular approach, using the concept of territorial metabolism designating the set of energy and material flows brought into play by the functioning of a given territory.
This approach consists of understanding cities as the result of a specific socio-ecological regime, no longer solely through their functions or activities, but through their flows and stocks of materials and resources. 
Indeed, cities worldwide are committed to becoming more circular in their resource use. 
Looping actions –reuse, recycling and recovery of resources (materials, energy, water, land and infrastructure)- can help to address resource scarcity and wastage in cities.
However, the major research problem is whether these actions truly help to reduce their environmental impacts10,11 and to overcome the many challenges to implementation (Institutional, Political, Regulatorial, Socio Economical)12.

Post-growth as alternative baseline for future scenarios
On the other hand, post-growth futures are united under the broad vision of an economy and society where the pursuit of economic growth is deprioritised in favour of social and environmental wellbeing. Wellbeing economics, doughnut economics, steady-state economics and degrowth are all forms of post-growth futures. These differ from one another primarily in their strategy for change. The degrowth proponents argue that economic growth cannot be sufficiently decoupled from environmental impacts, which renders further growth of the economy unsustainable13,14. The degrowth is considered the most ‘radical’ of the alternatives as it foregrounds the need to reconfigure the existing, capitalist, socio-economic structures and institutions of society and emphasises the need for developed economies to initiate a phase of shrinking material throughput to reach a sustainable steady-state. This is probably a transition that could take many years, including: redistribution of wealth and incomes; cooperative and sharing economies, including community-building initiatives like repair shops; localising the economy; and stronger participatory democracy. Given the broad ambition, this project will be mainly focused on how the strategies of local manufacturing/recycling at the urban third places can contribute to give insights for the post-growth economy.
‘Design global / Manufacturing local’ for a post-growth urban settlement
The mass and globalized production systems the fruit of a complex co-evolution of single unit productions and interconnected systems motivated by the growth and performance paradigm15. However, it is well known the several forms of environmental degradation have intensified without fully assuring the social foundation’s minimum standards (e.g. healthcare, energy, water)16 up to the point to consider the humanity as a geological force, which is recently considered the Anthropocene era17,18. Given that context, a major trend in the development of production systems seeks to establish an urban production model19–21,21 with decentralized and distributed characteristics22,23 as an alternative of globalized manufacturing values chains. Aiming at a ‘design global / manufacturing local’ (DGML)24 seems to be a prototype of industrialization transition that is taking place. DGML is an emerging productive model that builds on the convergence of the digital commons of knowledge, software and design with local manufacturing 

technologies. The Open Source Appropriate Technology (OSAT)25 and peer-to-peer (P2P)26 are seen as potential drivers to propose an alternative globalization manufacturing paradigm27.
Recently, in the framework of an EU H2020 project called INEDIT, at the ERPI Laboratory of the University of Lorraine, we are developing the “Do-It-Together” (DIT)28 concept as a form of participatory design and collaborative production strategy. The INEDIT project aims to create an open co-creation and manufacturing ecosystems to transform the Do-It-Yourself practices largely documented in FabLabs/Hacker/Maker spaces into a professional approach to capitalize the knowledge, creativity and ideas of design and engineering. This aims to prove the value of the integration of individuals/customer in all the processes of physical products manufacturing, from ideation to production. These radical means make DIT more suitable to small-scale production at local sites. Indeed, we have been leading the implementation of the ‘Green Fablab’ (https://lf2l.fr/projects/green-fablab/) demonstrator inside a third place called Octroi-Nancy Association (https://www.octroi-nancy.fr/) since November 2021. The Green Fablab is a distributed recycling demonstrator that uses a living lab approach29,30 to experiment in real conditions with citizens, final users and large general public. Distributed recycling refers to the use of recycled polymer wastes materials by means of a mechanical recycling process31. This marks the technical evolution of open source hardware including material-based additive manufacturing, injection and compression moulding enabling a new path for recycling and production units. This experiment is enframed as a design for sustainability at a spatio-social level32. This is only the start for exploring new socio-technical configurations.
The scientific problem: How to connect the dots of a City – Third Places – Products nexus.
The open manufacturing/recycling ecosystems at the urban third places are socio-technical systems that are still in its infancy stage. The holistic impact that these production alternatives in the context of an urban city suffers from the critical uncertainty of its relevance affecting the support and monitoring of this urban strategy. From the urban planning perspective, there are no methodological tools to evaluate the impact in the frame of an urban post-growth scenario. A trans-disciplinary approach is need to understand this problem.
Main Objective & Research questions
The purpose of this project is twofold: 1) The scientific understanding on how the urban open manufacturing/recycling ecosystems can be drivers for the territorial resilience giving insights for a post-growth regimen. 2) To define in what extent the open source design approach is an asset for the urban development. Particularly to tackle the waste management strategy for plastic waste recycling process.
The major gap that this project aims to tackle is to better understand the continuum knowledge and connection between the technical-facility-urban levels including the respective boundary objects33 that needs to be considered to go from the open manufacturing space (third place) to the urban planning sphere.
The main impact of this project is to develop a systemic aid decision tool using system dynamics approach to asses in what extent the alternative socio-technical productive models like third places are assets for territorial resilience under the conceptual framework of post-growth future.
Major long vision: Appropriate urban production
The major ambition of this project is how to design socio-technical ‘circular units’ for manufacturing that integrates values of sobriety, resilience34,35, adaptability36 and evolutive in urban settlements. The technologies that empower communities through access to means of production; promote localisation of production and logistics; tend to lean towards sufficiency and creativity; are easily and economically utilized from readily available resources by local communities; adopt the open-source philosophy; are designed for affordability and durability; explore tacit knowledge; are defined as Appropriate (in the sense


of Schumacher37) or Convivial (in the sense of Ivan Illich38). Appropriateness (or Conviviality) criteria may foster more systemic and thus sustainable design22,39,40.
Indeed, the reuse, repairing, recycling approaches will need to converge in a post-growth economy context considering the societal issues of resource scarcity and waste accumulation in the urban settlements14,41. Indeed, today the establishment of these socio-technical systems need to include all ecosystem externalities and the carrying capacity of the ecosystem to claim sustainability42,43. The trend is reinforced by the fact that by 2050, it is expected that about 70% of the world’s population will live in urban settlements41.
Introduction to the scientific methodology
This project implements an innovative methodology considering the urban, technical and valuation aspects. We discuss the methodologies that we plan to adopt.
The aim of WP1 is to set an integrative literature baseline of the urban territory in the frame of micro-value chains for manufacturing/recycling production. The major output is to present the indicators, criteria and sustainable principles in the lens of post-growth future. This working package gives the insights for the WP2, and WP3, which are key to the project. The WP2 to systematize a design process for Open Source Appropriate Technologies for a complete distributed manufacturing/recycling process of plastic recycling as lead material case study. The main idea is to establish a local recycling unit to connect with local designers/manufactures at the Octroi ecosystem in order to create experimental products for the local community. WP3 It aims to connect the urban and technical layers to better understand under which conditions the open manufacturing ecosystems are pertinent for an urban territory. This WP will synthetize an aid-decision tool in the means of system dynamics perspective to better understand the drivers, barriers and scenarios. This will reveal the value of these type of socio-technical systems given the challenges posed by the offshoring of global value chains in an urban territorial context to improve the resilience of the territory and making informed decisions on sustainability. WP4 is devoted to the iteration and evaluation using life cycle assessment of the urban production to deeply understand the possible evolution according to the particularities of the urban context of Nancy and the Octroi-Nancy Association. In this WP4 aims to consolidate the starting point for a longitudinal study to present the possible evolution and unfolding the major that a productive third place can impact the resilience of the local territory.
II. Partenariat (consortium ou équipe)
Laurent Dupont is a senior researcher at the ERPI laboratory (Research Team on innovative Processes, Université de Lorraine, France), lecturer at ENSGSI and visiting lecturer at TELECOM Nancy. He is the co-founder (2014) and scientific manager of the Lorraine Fab Living Lab® (www.LF2L.fr), the ERPI research platform for prospective assessment of innovative usages and innovation acceptability. He is also the co-creator (2008) and scientific coordinator of Lorraine Smart Cities Living Lab (ENoLL member since 2010), an interdisciplinary project involving several laboratories and other public and private partners. He designs, implements and evaluates new processes, based on collaborative innovation involving users, companies and territories, generating smart and sustainable Cities. He is member of ICE / IEEE ITMC International Organizing Committee, International Conference on Technology, Engineering & Innovation. www.ice-conference.org He also invited chair at VRIC - Virtual Reality International Conference since 2017 - https://www.laval-virtual.org/
Fabio Cruz is a research associate at the ERPI Laboratory. The main research interest relies on the distributed recycling via additive manufacturing (DRAM) as a possible socio-technical transition towards a sustainable manufacturing approach in a post-growth future alternative. I work specifically at the research platform Lorraine Fab Living Lab (LF2L) in the analysis and implementation of distributed recycling through the Green Fablab project. The work that we have developed so far is focused on the technical, logistical and system characterizations which are part of the scope in the validation of the DRAM.
